### ISSUE TITLE
Display Challenge DF rewards distribution system

### ISSUE THREAD

**Issue by KatunaNorbert** [oceanprotocol/df-web#592] opened 2023-06-27 11:09 UTC
Challenge DF rewards are distributed to the first 3 places based on best submission ranking.
Rewards for each place it's fixed and known before so it makes sense for us to make this visible to the users.

**Comment by KatunaNorbert** [comment] 2023-06-27 13:07
Example of design:

![Screenshot 2023-06-23 at 15.29.00.png](https://images.zenhubusercontent.com/5ff449b376fe2511ba59495d/92cf55ca-44c7-4a81-89d1-e5d230d42afb)

**Comment by idiom-bytes** [comment] 2023-06-27 18:05
Like I mentioned... I don't believe we should put that information/visual/styling there.. especially the podium.

In any CTA you don't want to overwhelm the user, [keep it brain-1](https://en.wikipedia.org/wiki/Thinking,_Fast_and_Slow).
The table below offers all the information needed (making the visual redundant).
"KISS"

If anything, let's keep these values out of the CTA and somewhere so they are clearly visible.

**Comment by KatunaNorbert** [comment] 2023-06-28 07:53
I think we should display them somewhere. If CTA it's not the right place then what would that be?
I don't think displaying key information like the fact that it's a competition and only the first 3 places are rewarded and the amount for each since that's known for us it's overwhelming, but quite important.

With relaying on the table we basically tell the user that this values are constant and they are not going to change. What if we change the rewards amount, which actually it's inevitable in the future? Should we expect the user to guess the reward for each place based on old rewards amount?

**Comment by idiom-bytes** [comment] 2023-07-06 14:15
Is #605 a duplicate of this?
Can we close that one and build it out here?

I am recommending we implement the following version
![Screenshot from 2023-07-06 06-51-29](https://github.com/oceanprotocol/df-web/assets/69865342/091e3ed4-a78f-4792-a2f2-975cb6429fc9)

**Comment by KatunaNorbert** [comment] 2023-07-06 14:29
They are related but wouldn't say it's a duplicate. That issue was refering to the whole section while this is mainly about displaying the rewards for each place.

I like the design so we could go with this one.

**Closed** 2023-07-19 08:33 UTC
Labels: Type: Enhancement
