### ISSUE TITLE
Est. passive/active yield on rewards page is difficult to understand

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/df-web#478] opened 2023-02-25 19:32 UTC
### Problem:
We got some feedback: "Right now APY is still hard to understand."

We have implemented a solution (Cand A) previously similar to what trent mentioned below (CandB) but it focused around the global APY vs. your local APY.

All of this is described in the tooltip of the dapp.
We have also been iterated on the docs wrt these calculations.

### Candidate Solution
Improve UX/UI to better display APY and expected rewards from system.

Cand A (Right now): Show global/yours for this week if you're connected.
Cand B: Show last/cur week estimates for passive/active rewards.

Feedback: "Currently, we do not offer a clear way for users to understand the exact amount of rewards they can expect to receive. Another possible solution is displaying the expected APY in the lock screen which is better than the previous solution I think."

**Comment by trentmc** [comment] 2023-02-27 08:46
Please revise this github issue where the title is problem, or problem + proposed solution. E.g. call it "It's difficult to tell what APY to expect"

> Show expected APY inside of Passive/Active Reward Cards
I disagree with this proposed solution.

We should show _both_.

The most important thing is for the identify guess what their APY might be. 

But then, where might that come from? There are two dimensions: 
- the decomposition of total APY from: (a) passive rewards (b) active rewards APY. Think of this as the first-level "drill-down".
- time. (a) APYs from the past 1+ weeks; and (b) expected APY for current week.

Overall, it could be presented succinctly as a matrix:

| Rewards | Last week | Expected this week |
| ----           | ----            | ---- |
| **Total**   | **11.9%** | **11.7%** |
| Passive   | 8.5%         | 8.2% |
| Active      | 3.1%         | 3.2% |

Where
- If wallet isn't connected, it shows average (or median). Otherwise it shows the actual user's numbers. Similar to now.
- And we need to fix "Active" * "Expected this week". Currently we show that, but it uses DCV _so far_, which is typically a value of 0 until the very end of the DF Round, when consume tends to happen. I recommend instead to change the calc to use max(DCV last week, DCV so far this week) across the appropriate data assets.

**Comment by KatunaNorbert** [comment] 2023-02-27 12:41
I agree with adding an expected APY near the lock screen where the user can see how much he can gain before locking his tokens. We can still discuss what that APY contains(passive, passive + active, passive + active + publisher in future)

About the Active APY for this week, I don't know how well we can expect it, probably the easiest way would be to base it on last weeks data. The problem is that with all the wash consume going on it would be pretty inaccurate. I would prefer to show a max APY for active and then show how the APY evolves during the week(as it is right now).

**Comment by trentmc** [comment] 2023-05-04 01:49
A lot of work has been done on this issue since it was created. These days we're ok "ok" shape. Any further work is low priority for the foreesable future. When we want to improve again, it will rear its head readily. 

So, closing.

**Closed by trentmc** 2023-05-04 01:49 UTC
Labels: Type: Enhancement, Priority: High
